default: &DEFAULT

  # Weights and biases
  wandb:
    log: False
    name: "CHECK PLOTS AND SUMMARY STUFF" # If None, config will be used but you can override it here
    group: "fno-v1"
    files_to_save:
      - "/Users/u235567/Desktop/cs-165-final-project/data.py"
      - "/Users/u235567/Desktop/cs-165-final-project/main.py"
      - "/Users/u235567/Desktop/cs-165-final-project/evaluation.py"
      - "/Users/u235567/Desktop/cs-165-final-project/model_params.py"
      - "/Users/u235567/Desktop/cs-165-final-project/model.py"
      - "/Users/u235567/Desktop/cs-165-final-project/plotting.py"
      - "/Users/u235567/Desktop/cs-165-final-project/printing.py"
      - "/Users/u235567/Desktop/cs-165-final-project/seq_to_label.py"
      - "/Users/u235567/Desktop/cs-165-final-project/seq_to_seq.py"
      - "/Users/u235567/Desktop/cs-165-final-project/utils.py"
  
  optuna: 
    use_optuna: False
    num_trials: 15
    num_jobs: 4

  seed: 50 # 42

  # Training Parameters
  training:
    epochs: 2 #500
    save_checkpoint: True
    model_type: "fno"
    testing_for_debugging: False
    batch_size: 64
    # for learing rate scheduler
    learning_rate_scheduler_target: 1e-5 # 1e-4
    learning_rate_adam: 1e-3
    learning_rate_init: 1e-6  # for warmup
    warmup_steps: 50
    lr_scheduler_type: "StepLR" #"linear"
    step_size: 25 # 40 was not so good, go lower. 20 best for 100 epochs
    gamma: 0.5
    # for adam optimizer
    adam_weight_decay: 0.01
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_eps: 1e-8
    # for FNO model
    curriculum_steps: 0
    mlp_dropout: 0
    n_modes: 16
    hidden_channels: 64
    n_layers: 4
    
    reg_to_class: # from regression to classification
      threshold: 0.6
      softmax_before_mean: False # if False, the softmax is done after mean
  
  balance_classes:
    balanced_loss: False
    pos_weight_emphasis_factor: 1.0 #1.5 will weight disruptions more than ratio; see if undersampling makes is enough first.
    undersample: False
    undersample_ratio: 0.5 #2.0 number of times there are MORE non-disruptions than disruptions
    data_augmentation_windowing: False 
    # Ratio of augmented data to original data.
    data_augmentation_ratio: 2
    disruptivity_distance_window_length: 0 #8 # for sliding window

  # Dataset related Parameters
  data:
    filename: "Full_HDL_dataset_unnormalized_no_nan_column_names_w_shot_and_time.pickle"
    folder: "" #"tokamak/Transformers-Plasma-Disruption-Prediction-autoformer/Model_training"
    dataset_type: "seq_to_label" #"state"
    max_length: 2048
    scaling_type: "standard" #"robust" "none"
    # used to determine deterministic label of shots with probabilistic label
    cmod_hyperparameter_non_disruptions: 0.1
    cmod_hyperparameter_disruptions: 0.9
    d3d_hyperparameter_non_disruptions: 0.1
    d3d_hyperparameter_disruptions: 0.9
    east_hyperparameter_non_disruptions: 0.05
    east_hyperparameter_disruptions: 0.92
    end_cutoff_timesteps: 0 #50 #8 # microseconds
    end_cutoff_timesteps_test: 8
    case_number: 8 #12 #6
    tau_cmod: 12 # TODO: ASK: Is this a time constant associated with tokamak?
    tau_d3d: 35
    tau_east: 75
    standardize_disruptivity_plot_length: True
    use_smoothed_tau: True
    data_context_length: 100
    fix_sampling: True # equal spaced timesteps, but can vary across machines
    standardize_sampling_rate: False # whether to force all machines to have same sampling rate for each timestep. If true, resample rate defaults to .005
    smooth_v_loop: True
    v_loop_smoother: 10
    uniform_seq_length: False
    probabilistic_labels: True
    delta_t: 150 #1000 #1000 #50  # uniform sequence length, only used if uniform_seq_length is True

  # Evaluation Parameters
  eval:
    eval_high_thresh: 0.8
    eval_low_thresh: 0.5
    eval_hysteresis: 2
    sweep_id: None
    unrolled_smoothing: 10

